include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - build/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_final_fields
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - always_use_package_imports
    - empty_catches
    - no_duplicate_case_values
    - null_closures
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_statements
